publicDomain: "https://bs.samt.st"
databasePath: data/sqlite.db

allowedMimeTypes:
  - image/jpeg
  - image/jpg
  - image/png
  - image/gif
  - image/webp
  - video/mp4
  - video/webm

dashboard:
  enabled: true
  username: admin
  password: pass

storage:
  backend: local
  local:
    dir: ./data/blobs

upload:
  enabled: true
  requireAuth: false         # turn off for quick testing, then re-enable
  # allowList: []
  allowedMimeTypes:
    - image/jpeg
    - image/jpg
    - image/png
    - image/gif
    - image/webp
    - video/mp4
    - video/webm

media:
  enabled: true
  requireAuth: false         # turn off for quick testing, then re-enable
