publicDomain: "https://bs.samt.st"
databasePath: data/sqlite.db

dashboard:
  enabled: true
  username: admin
  password: pass

storage:
  backend: local
  local:
    dir: ./data/blobs
  # Rules determine what blobs are accepted and how long they're kept
  rules:
    - type: "image/*"
      expiration: 1 month
    - type: "video/*"
      expiration: 1 month
    - type: "*"
      expiration: 1 week

upload:
  enabled: true
  requireAuth: false         # turn off for quick testing, then re-enable

media:
  enabled: true
  requireAuth: false         # turn off for quick testing, then re-enable
